/**
 * Embedded Google Fonts catalog, preserved in source order.
 *
 * This is metadata only: importing it never requests a stylesheet or font file.
 * GXUFY deliberately keeps loading behind the existing selected-font overlay
 * path instead of eager/background preview loading.
 */
export const GOOGLE_FONT_FAMILIES = [
  'ABeeZee',
  'Acme',
  'Alegreya',
  'Alegreya Sans',
  'Alfa Slab One',
  'Anton',
  'Archivo',
  'Archivo Black',
  'Archivo Narrow',
  'Arimo',
  'Asap',
  'Audiowide',
  'Bakbak One',
  'Bangers',
  'Barlow',
  'Barlow Condensed',
  'Bebas Neue',
  'Bitter',
  'Black Ops One',
  'Bungee',
  'Cabin',
  'Cairo',
  'Catamaran',
  'Caveat',
  'Chakra Petch',
  'Cinzel',
  'Comfortaa',
  'Comic Neue',
  'Concert One',
  'Cormorant Garamond',
  'Creepster',
  'Crimson Text',
  'Dancing Script',
  'DM Sans',
  'Dosis',
  'EB Garamond',
  'Exo',
  'Exo 2',
  'Fira Code',
  'Fira Sans',
  'Fira Sans Condensed',
  'Fjalla One',
  'Fredoka',
  'Fugaz One',
  'Geologica',
  'Goldman',
  'Heebo',
  'Hind',
  'IBM Plex Mono',
  'IBM Plex Sans',
  'Inconsolata',
  'Indie Flower',
  'Inter',
  'JetBrains Mono',
  'Josefin Sans',
  'Jost',
  'Kanit',
  'Karla',
  'Kalam',
  'Lato',
  'League Spartan',
  'Lexend',
  'Libre Baskerville',
  'Libre Franklin',
  'Lilita One',
  'Lobster',
  'Lobster Two',
  'Lora',
  'Luckiest Guy',
  'Manrope',
  'Maven Pro',
  'Merriweather',
  'Merriweather Sans',
  'Montserrat',
  'Montserrat Alternates',
  'Mulish',
  'Nanum Gothic',
  'Noto Sans',
  'Noto Sans JP',
  'Noto Serif',
  'Nunito',
  'Nunito Sans',
  'Open Sans',
  'Orbitron',
  'Oswald',
  'Outfit',
  'Overpass',
  'Oxanium',
  'Pacifico',
  'Patrick Hand',
  'Paytone One',
  'Permanent Marker',
  'Philosopher',
  'Play',
  'Playfair Display',
  'Plus Jakarta Sans',
  'Poppins',
  'Press Start 2P',
  'Prompt',
  'PT Sans',
  'PT Serif',
  'Quicksand',
  'Rajdhani',
  'Raleway',
  'Righteous',
  'Roboto',
  'Roboto Condensed',
  'Roboto Mono',
  'Roboto Slab',
  'Rubik',
  'Russo One',
  'Sacramento',
  'Saira',
  'Satisfy',
  'Secular One',
  'Shadows Into Light',
  'Signika',
  'Silkscreen',
  'Source Code Pro',
  'Source Sans 3',
  'Space Grotesk',
  'Space Mono',
  'Spectral',
  'Staatliches',
  'Teko',
  'Titan One',
  'Titillium Web',
  'Ubuntu',
  'Ubuntu Mono',
  'Unbounded',
  'Varela Round',
  'Vollkorn',
  'Work Sans',
  'Yanone Kaffeesatz',
  'Zilla Slab',
] as const;
